export const
  NEW_GAME = 'NEW_GAME',
  DISPLAY_PLAYER_VIEW = 'DISPLAY_PLAYER_VIEW',
  DISPLAY_SPECTATOR_VIEW = 'DISPLAY_SPECTATOR_VIEW',
  PLAY_MOVE = 'PLAY_MOVE',
  NOTIFY_MOVES = 'NOTIFY_MOVES',
  CANCEL_MOVE = 'CANCEL_MOVE',
  END_TRANSITION = 'END_TRANSITION'