export const
  NEW_GAME = 'NEW_GAME',
  DISPLAY_PLAYER_VIEW = 'DISPLAY_PLAYER_VIEW',
  DISPLAY_SPECTATOR_VIEW = 'DISPLAY_SPECTATOR_VIEW',
  PLAY_MOVE = 'PLAY_MOVE',
  NOTIFY_MOVES = 'NOTIFY_MOVES',
  START_ANIMATION = 'START_ANIMATION',
  APPLY_ANIMATING_MOVE = 'APPLY_ANIMATING_MOVE',
  END_ANIMATION = 'END_ANIMATION',
  CANCEL_MOVE = 'CANCEL_MOVE'
