export const
  NEW_GAME = 'NEW_GAME',
  DISPLAY_PLAYER_VIEW = 'DISPLAY_PLAYER_VIEW',
  DISPLAY_SPECTATOR_VIEW = 'DISPLAY_SPECTATOR_VIEW',
  PLAY_MOVE = 'PLAY_MOVE',
  SERVER_NOTIFICATION = 'SERVER_NOTIFICATION',
  RESUME = 'RESUME',
  UNDO_MOVE = 'UNDO_MOVE',
  MOVE_BACK = 'MOVE_BACK',
  MOVE_FORWARD = 'MOVE_FORWARD'
