export const CREATURE_TOKEN = 'CREATURE_TOKEN'
export const ARTEMIA_TOKEN = 'ARTEMIA_TOKEN'
export const TARGET_TOKEN = 'TARGET_TOKEN'
export const HUNT_TOKENS = [CREATURE_TOKEN, ARTEMIA_TOKEN, TARGET_TOKEN]